/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateWhiteCardArgs } from "./CreateWhiteCardArgs";
import { UpdateWhiteCardArgs } from "./UpdateWhiteCardArgs";
import { DeleteWhiteCardArgs } from "./DeleteWhiteCardArgs";
import { WhiteCardFindManyArgs } from "./WhiteCardFindManyArgs";
import { WhiteCardFindUniqueArgs } from "./WhiteCardFindUniqueArgs";
import { WhiteCard } from "./WhiteCard";
import { RoundFindManyArgs } from "../../round/base/RoundFindManyArgs";
import { Round } from "../../round/base/Round";
import { Deck } from "../../deck/base/Deck";
import { Player } from "../../player/base/Player";
import { WhiteCardService } from "../whiteCard.service";

@graphql.Resolver(() => WhiteCard)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class WhiteCardResolverBase {
  constructor(
    protected readonly service: WhiteCardService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "WhiteCard",
    action: "read",
    possession: "any",
  })
  async _whiteCardsMeta(
    @graphql.Args() args: WhiteCardFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [WhiteCard])
  @nestAccessControl.UseRoles({
    resource: "WhiteCard",
    action: "read",
    possession: "any",
  })
  async whiteCards(
    @graphql.Args() args: WhiteCardFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<WhiteCard[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "WhiteCard",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => WhiteCard, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "WhiteCard",
    action: "read",
    possession: "own",
  })
  async whiteCard(
    @graphql.Args() args: WhiteCardFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<WhiteCard | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "WhiteCard",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => WhiteCard)
  @nestAccessControl.UseRoles({
    resource: "WhiteCard",
    action: "create",
    possession: "any",
  })
  async createWhiteCard(
    @graphql.Args() args: CreateWhiteCardArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<WhiteCard> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "WhiteCard",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"WhiteCard"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        deck: args.data.deck
          ? {
              connect: args.data.deck,
            }
          : undefined,

        players: args.data.players
          ? {
              connect: args.data.players,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => WhiteCard)
  @nestAccessControl.UseRoles({
    resource: "WhiteCard",
    action: "update",
    possession: "any",
  })
  async updateWhiteCard(
    @graphql.Args() args: UpdateWhiteCardArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<WhiteCard | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WhiteCard",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"WhiteCard"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          deck: args.data.deck
            ? {
                connect: args.data.deck,
              }
            : undefined,

          players: args.data.players
            ? {
                connect: args.data.players,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => WhiteCard)
  @nestAccessControl.UseRoles({
    resource: "WhiteCard",
    action: "delete",
    possession: "any",
  })
  async deleteWhiteCard(
    @graphql.Args() args: DeleteWhiteCardArgs
  ): Promise<WhiteCard | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Round])
  @nestAccessControl.UseRoles({
    resource: "WhiteCard",
    action: "read",
    possession: "any",
  })
  async rounds(
    @graphql.Parent() parent: WhiteCard,
    @graphql.Args() args: RoundFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Round[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Round",
    });
    const results = await this.service.findRounds(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Deck, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "WhiteCard",
    action: "read",
    possession: "any",
  })
  async deck(
    @graphql.Parent() parent: WhiteCard,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Deck | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Deck",
    });
    const result = await this.service.getDeck(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => Player, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "WhiteCard",
    action: "read",
    possession: "any",
  })
  async players(
    @graphql.Parent() parent: WhiteCard,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Player | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Player",
    });
    const result = await this.service.getPlayers(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
