/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateBlackCardArgs } from "./CreateBlackCardArgs";
import { UpdateBlackCardArgs } from "./UpdateBlackCardArgs";
import { DeleteBlackCardArgs } from "./DeleteBlackCardArgs";
import { BlackCardFindManyArgs } from "./BlackCardFindManyArgs";
import { BlackCardFindUniqueArgs } from "./BlackCardFindUniqueArgs";
import { BlackCard } from "./BlackCard";
import { RoundFindManyArgs } from "../../round/base/RoundFindManyArgs";
import { Round } from "../../round/base/Round";
import { Deck } from "../../deck/base/Deck";
import { BlackCardService } from "../blackCard.service";

@graphql.Resolver(() => BlackCard)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class BlackCardResolverBase {
  constructor(
    protected readonly service: BlackCardService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "BlackCard",
    action: "read",
    possession: "any",
  })
  async _blackCardsMeta(
    @graphql.Args() args: BlackCardFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [BlackCard])
  @nestAccessControl.UseRoles({
    resource: "BlackCard",
    action: "read",
    possession: "any",
  })
  async blackCards(
    @graphql.Args() args: BlackCardFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<BlackCard[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "BlackCard",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => BlackCard, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "BlackCard",
    action: "read",
    possession: "own",
  })
  async blackCard(
    @graphql.Args() args: BlackCardFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<BlackCard | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "BlackCard",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => BlackCard)
  @nestAccessControl.UseRoles({
    resource: "BlackCard",
    action: "create",
    possession: "any",
  })
  async createBlackCard(
    @graphql.Args() args: CreateBlackCardArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<BlackCard> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "BlackCard",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"BlackCard"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        deck: args.data.deck
          ? {
              connect: args.data.deck,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => BlackCard)
  @nestAccessControl.UseRoles({
    resource: "BlackCard",
    action: "update",
    possession: "any",
  })
  async updateBlackCard(
    @graphql.Args() args: UpdateBlackCardArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<BlackCard | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "BlackCard",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"BlackCard"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          deck: args.data.deck
            ? {
                connect: args.data.deck,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => BlackCard)
  @nestAccessControl.UseRoles({
    resource: "BlackCard",
    action: "delete",
    possession: "any",
  })
  async deleteBlackCard(
    @graphql.Args() args: DeleteBlackCardArgs
  ): Promise<BlackCard | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Round])
  @nestAccessControl.UseRoles({
    resource: "BlackCard",
    action: "read",
    possession: "any",
  })
  async rounds(
    @graphql.Parent() parent: BlackCard,
    @graphql.Args() args: RoundFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Round[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Round",
    });
    const results = await this.service.findRounds(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Deck, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "BlackCard",
    action: "read",
    possession: "any",
  })
  async deck(
    @graphql.Parent() parent: BlackCard,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Deck | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Deck",
    });
    const result = await this.service.getDeck(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
