/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DeckWhereUniqueInput } from "../../deck/base/DeckWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { RoundListRelationFilter } from "../../round/base/RoundListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
@InputType()
class BlackCardWhereInput {
  @ApiProperty({
    required: false,
    type: () => DeckWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DeckWhereUniqueInput)
  @IsOptional()
  @Field(() => DeckWhereUniqueInput, {
    nullable: true,
  })
  deck?: DeckWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  discarded?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => RoundListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RoundListRelationFilter)
  @IsOptional()
  @Field(() => RoundListRelationFilter, {
    nullable: true,
  })
  rounds?: RoundListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  text?: StringNullableFilter;
}
export { BlackCardWhereInput };
