/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateDeckArgs } from "./CreateDeckArgs";
import { UpdateDeckArgs } from "./UpdateDeckArgs";
import { DeleteDeckArgs } from "./DeleteDeckArgs";
import { DeckFindManyArgs } from "./DeckFindManyArgs";
import { DeckFindUniqueArgs } from "./DeckFindUniqueArgs";
import { Deck } from "./Deck";
import { BlackCardFindManyArgs } from "../../blackCard/base/BlackCardFindManyArgs";
import { BlackCard } from "../../blackCard/base/BlackCard";
import { WhiteCardFindManyArgs } from "../../whiteCard/base/WhiteCardFindManyArgs";
import { WhiteCard } from "../../whiteCard/base/WhiteCard";
import { Game } from "../../game/base/Game";
import { DeckService } from "../deck.service";

@graphql.Resolver(() => Deck)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class DeckResolverBase {
  constructor(
    protected readonly service: DeckService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Deck",
    action: "read",
    possession: "any",
  })
  async _decksMeta(
    @graphql.Args() args: DeckFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Deck])
  @nestAccessControl.UseRoles({
    resource: "Deck",
    action: "read",
    possession: "any",
  })
  async decks(
    @graphql.Args() args: DeckFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Deck[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Deck",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Deck, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Deck",
    action: "read",
    possession: "own",
  })
  async deck(
    @graphql.Args() args: DeckFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Deck | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Deck",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Deck)
  @nestAccessControl.UseRoles({
    resource: "Deck",
    action: "create",
    possession: "any",
  })
  async createDeck(
    @graphql.Args() args: CreateDeckArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Deck> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Deck",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Deck"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        game: args.data.game
          ? {
              connect: args.data.game,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Deck)
  @nestAccessControl.UseRoles({
    resource: "Deck",
    action: "update",
    possession: "any",
  })
  async updateDeck(
    @graphql.Args() args: UpdateDeckArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Deck | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Deck",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Deck"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          game: args.data.game
            ? {
                connect: args.data.game,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Deck)
  @nestAccessControl.UseRoles({
    resource: "Deck",
    action: "delete",
    possession: "any",
  })
  async deleteDeck(@graphql.Args() args: DeleteDeckArgs): Promise<Deck | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [BlackCard])
  @nestAccessControl.UseRoles({
    resource: "Deck",
    action: "read",
    possession: "any",
  })
  async blackCards(
    @graphql.Parent() parent: Deck,
    @graphql.Args() args: BlackCardFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<BlackCard[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "BlackCard",
    });
    const results = await this.service.findBlackCards(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [WhiteCard])
  @nestAccessControl.UseRoles({
    resource: "Deck",
    action: "read",
    possession: "any",
  })
  async whiteCards(
    @graphql.Parent() parent: Deck,
    @graphql.Args() args: WhiteCardFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<WhiteCard[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "WhiteCard",
    });
    const results = await this.service.findWhiteCards(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Game, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Deck",
    action: "read",
    possession: "any",
  })
  async game(
    @graphql.Parent() parent: Deck,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Game | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Game",
    });
    const result = await this.service.getGame(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
