/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { RoundCreateNestedManyWithoutPlayersInput } from "./RoundCreateNestedManyWithoutPlayersInput";
import { ValidateNested, IsOptional, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { GameWhereUniqueInput } from "../../game/base/GameWhereUniqueInput";
import { WhiteCardCreateNestedManyWithoutPlayersInput } from "./WhiteCardCreateNestedManyWithoutPlayersInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
@InputType()
class PlayerCreateInput {
  @ApiProperty({
    required: false,
    type: () => RoundCreateNestedManyWithoutPlayersInput,
  })
  @ValidateNested()
  @Type(() => RoundCreateNestedManyWithoutPlayersInput)
  @IsOptional()
  @Field(() => RoundCreateNestedManyWithoutPlayersInput, {
    nullable: true,
  })
  czars?: RoundCreateNestedManyWithoutPlayersInput;

  @ApiProperty({
    required: false,
    type: () => GameWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GameWhereUniqueInput)
  @IsOptional()
  @Field(() => GameWhereUniqueInput, {
    nullable: true,
  })
  game?: GameWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => WhiteCardCreateNestedManyWithoutPlayersInput,
  })
  @ValidateNested()
  @Type(() => WhiteCardCreateNestedManyWithoutPlayersInput)
  @IsOptional()
  @Field(() => WhiteCardCreateNestedManyWithoutPlayersInput, {
    nullable: true,
  })
  hand?: WhiteCardCreateNestedManyWithoutPlayersInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  score?: number | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}
export { PlayerCreateInput };
